site_name: Agile Grasper Documentation
repo_url: https://github.com/shadow-robot/agile_grasper_documentation.git

copyright: "Copyright © 2018 Shadow Robot Company"
theme: readthedocs

pages:
- Home: index.md
- User Documentation:
    - 'Setting up the grasper': 'user_guide/setting_up_the_grasper.md'
    - 'Getting started': 'user_guide/getting_started.md'
    - 'Mechanical Description of the Grasper': 'user_guide/mechanical_description.md'
    - 'Maintaining the Grasper': 'user_guide/maintaining_grasper.md'
    - 'Peripherals': 'user_guide/peripherals.md'
    - 'FAQ': 'user_guide/FAQ.md'
